# This sets trigger to any update in master  
# trigger:
# - master

#  Defines the host for agent (MS hosted)
pool:
  vmImage: 'ubuntu-latest'

#  Build steps for the pipeline
steps:
- script: npm ci
  displayName: 'Installing node modules'

- script: npm run lint
  displayName: 'Checking for lint errors'

- script: |
    npm run build
  displayName: 'Running webpack build'

- script: |
    npm run cypress:ci
  displayName: 'Running cypress tests'

# Save artifacts to refer them in release builds
- task: PublishPipelineArtifact@1
  inputs:
    path: $(Agent.BuildDirectory)/s/build
    artifact: react-static-website-build-artifacts